### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [ApolloDatapacks/tectonic#6] opened 2022-10-11 15:01 UTC
crashes when generating world https://mclo.gs/FNBkCMb

**Comment by Aces-and-Jacks** [comment] 2022-10-11 15:08
I saw in a post you said to install https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric and it worked

Would you be able to show this as a dependency?

**Comment by ApolloDatapacks** [comment] 2022-10-11 22:17
I found the root cause of the crash and fixed it. v1.0.2 should drop the requirement of Cyanide.

**Comment by ApolloDatapacks** [comment] 2022-10-12 05:49
Closing issue, the crash with Terrablender installed has been fixed in v1.0.1a. Cyanide is still required for BYG/BOP compatibility and still shows that on the wiki.

**Closed by ApolloDatapacks** 2022-10-12 05:49 UTC
Labels: bug, compatibility, crash
